### ISSUE TITLE
Incorrect tag in example.

### ISSUE THREAD

**Issue by latentflip** [prosody/prosody-docker#11]
I have no idea what I'm doing with docker, but I just tried running the example, and it said it couldn't find tag 0.9 which makes sense giving: https://registry.hub.docker.com/u/prosody/prosody/tags/manage/

I would have just PR'd but dunno which tag you'd want to use for the example.

<3

**Comment by mwild1** [comment]
Hi Philip, thanks for the report!

Actually the example is correct... but the tag is inexplicably missing :)

It's supposed to be created by our build system, but it appears this hasn't worked for our 0.9 branch. I'll look into it...

**Comment by latentflip** [comment]
Okay, now that I've finally got things running, it looks like there's a few other issues in the example.

* -v seems to be `-v /local/path:/docker/path`
* the image needs to go at the end or the other config gets ignored.

so more like:

```
docker run -d \
   -p 5222:5222 \
   -p 5269:5269 \
   -p localhost:5347:5347 \
   -e LOCAL=romeo \
   -e DOMAIN=shakespeare.lit \
   -e PASSWORD=juliet4ever \
   -v /data/prosody/configuration:/etc/prosody  \
   -v /logs/prosody:/var/log/prosody  \
   -v /data/prosody/modules:/usr/lib/prosody-modules  \
   prosody/prosody:0.9 
```

Again, I could be all wrong, but that's the only way I've managed to get it working.

**Comment by lloydwatkin** [comment]
All correct @latentflip as I discovered myself on friday, will update the example now. The issue with knowing how to do it on the command line but then translating it badly to the documentation :)

**Comment by mwild1** [comment]
Fixed the issue that caused the tags to get out of date (and missing). They should start updating/appearing shortly.
