### ISSUE TITLE
The Docker Hub image appears to be out of date

### ISSUE THREAD

**Issue by dwilson6** [prosody/prosody-docker#12]
I was trying to use the prosody docker image and noticed that the image in the registry is out of date compared to the Dockerfile in this repo.  The entrypoint.sh isn't part of the latest image so creating a user on startup doesn't work.  Would you be able to push a new image to the registry? In the mean time I can build it locally.

I was also having trouble with the logs volume because the directory on the host didn't have the permissions set right.  That might be worth noting in the README.

**Comment by dougborg** [comment]
Please consider implementing an automated build that consumes released versions of Prosody for the docker container hosted on the docker hub and that gets updated automatically when your ubuntu base image changes.

**Comment by lloydwatkin** [comment]
@dwilson6 a pull request updating the instructions would be great

@mwild1 it seems the build server isn't doing what it is supposed to be doing :)

@dougborg we can't currently do automated builds since the docker hub won't pull from a custom mercurial repo, and the team doesn't want to use github.

**Comment by mwild1** [comment]
Between this and issue #11, yes - looks like the build server isn't behaving. I don't have time today, but I'll take a look at it tomorrow and get it working again.

**Comment by mwild1** [comment]
Just had a chance to look at the build server while preparing the new release. Found and fixed the issue that was making Docker builds fail. You should see new images start to appear over the coming hours as all our branches get rebuilt. Enjoy!
