### ISSUE TITLE
How to add users to a starting container?

### ISSUE THREAD

**Issue by mpas** [prosody/prosody-docker#16]
Sorry to post a question over here but i am looking for ways to get an initial userlist into the container. I am able to create the initial user using the environment variables `LOCAL, DOMAIN, and PASSWORD`. 

But i am looking for ways to create a list of users when the containers starts without manually needing to attach to the docker image and executing the `prosodyctl register local domain password`

I am trying to container to be used on our integration tests.

**Comment by mwild1** [comment]
Hi. There are several options:

The easiest is in-band registration, which is widely supported by XMPP clients and libraries: https://prosody.im/doc/creating_accounts#in-band_registration

You could also use mod_register_json: https://code.google.com/p/prosody-modules/wiki/mod_register_json

There are also the various admin interfaces, mod_admin_telnet, mod_admin_adhoc, etc.

Finally, if the test accounts for your integration tests are static, you can just create them with any method and then preserve the Prosody data directory and attach it to your container.
