### ISSUE TITLE
Please build a new version of the docker image

### ISSUE THREAD

**Issue by stapelberg** [prosody/prosody-docker#21]
As mentioned in #20, it’d be great if you could build a new docker image. The latest one as of now still uses the old entrypoint, which does not allow for parameters and insists on running `prosodyctl register`.

Thanks!

**Comment by mwild1** [comment]
I just cut a new release (1.3.0) of the build scripts. I'll update the Prosody build server to the new release shortly.

**Comment by mwild1** [comment]
Done. New releases and nightly builds will use the updated Dockerfile and entrypoint.

**Comment by stapelberg** [comment]
@mwild1 https://hub.docker.com/r/prosody/prosody/tags/ still says “last pushed: 21 days ago”. Are you sure everything is in order? Given that your last comment was 3 days ago, I would’ve expected a new nightly version to be up on the Docker Hub by now, or am I misunderstanding how the nightly builds work?

**Comment by mwild1** [comment]
You're right, I'm working on it. Not sure what's wrong, as the log shows the push succeeding. It might be that we're running an older version of docker though, so I'm upgrading. Will keep you posted :)

**Comment by mwild1** [comment]
Upgraded the build server, and our docker version. I manually ran the build script, and it appears to have succeeded. I pushed 0.10 and trunk based on the latest prosody-docker. Give them a spin and let me know how it goes.

**Comment by mwild1** [comment]
Commits to the 0.9 branch triggered the image for that to be updated also. Looks like it's working!

**Comment by stapelberg** [comment]
Thanks, pulling the 0.10 tag works. I’m not 100% certain what the version number is since prosody doesn’t log that when starting (I suggest it should :)).

The “latest” tag wasn’t changed. Can we make “latest” point to the latest stable version? AIUI, that’d be 0.10 in this case, yes?

**Comment by mwild1** [comment]
First thing at startup, Prosody logs: "Hello and welcome to Prosody version XXXXX". I get this:

```
$ sudo docker run -v "$PWD/prosody.cfg.lua":/etc/prosody/prosody.cfg.lua prosody/prosody:0.10
general             info	Hello and welcome to Prosody version 0.10 nightly build 188 (2015-12-15, 9beba2572e2b)
```

You just have to make sure your logging goes to the console. One of my upcoming tasks is figuring out a good default config for our Docker builds (though under normal circumstances it's going to be overridden, it's nice to have something working well by default).

The 'latest' tag is the last stable release, which is 0.9.8. That's still using the old Dockerfile currently, but we'll be announcing 0.9.9 soon, which will be tagged '0.9.9' and 'latest' when it's released.

**Comment by stapelberg** [comment]
Turns out the reason why I wasn’t seeing info messages was because I was using:

```
log = {
        { levels = { "debug" }; to = "console";  };
}
```

Once I changed it to the following, I started seeing info messages:

```
log = {
        debug = "*console";
}
```

Not quite sure whether that’s a bug, or expected behavior for some strange reason :).

**Comment by mwild1** [comment]
Expected behaviour, as 'levels' is a list of levels to log, and you only listed 'debug'. We tend to discourage that format now, as people rarely need such fine-grained control of their logging. The second format is simpler, it automatically treats it as 'debug and higher'.

For more info see https://prosody.im/doc/logging and https://prosody.im/doc/advanced_logging
