### ISSUE TITLE
Please build a new version of this Dockerfile (for OpenSSL)

### ISSUE THREAD

**Issue by stapelberg** [prosody/prosody-docker#26]
The version of OpenSSL installed in `prosody/prosody:0.10` is `1.0.1f-1ubuntu2.16`:
```
$ docker pull prosody/prosody:0.10                                          
0.10: Pulling from prosody/prosody

d634beec75db: Already exists 
51997bb91e33: Already exists 
943ed270d833: Already exists 
9bf90931f8d6: Already exists 
fded81ee9082: Already exists 
dd68caa977e3: Already exists 
54048d825eef: Already exists 
1c1f5c526ac7: Already exists 
4e4b41754701: Already exists 
fa846ffbdc31: Already exists 
6d980665df17: Already exists 
1441909bebc2: Already exists 
4b8e0bddfa3e: Already exists 
e165e925754f: Already exists 
Digest: sha256:51e5b38ccc97c153cf0fec06129de82e1fc5e2ec31e81931c57ca944172e3e82
Status: Image is up to date for prosody/prosody:0.10

$ docker run -entrypoint /bin/bash prosody/prosody:0.10 -c 'dpkg -l openssl'
Warning: '-entrypoint' is deprecated, it will be replaced by '--entrypoint' soon. See usage.
WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                            Version                         Architecture Description
+++-===============================-===============================-============-===============================================================================
ii  openssl                         1.0.1f-1ubuntu2.16              amd64        Secure Sockets Layer toolkit - cryptographic utility
```

There are two newer releases since then which address a bunch of security issues, see http://changelogs.ubuntu.com/changelogs/pool/main/o/openssl/openssl_1.0.1f-1ubuntu2.18/changelog

Can you please rebuild and push the docker image so that your users get these security fixes?

**Comment by stapelberg** [comment]
Also consider converting the docker repository to a docker automated build. With the automated build feature, you can have the docker hub rebuild your package for you whenever one of the dependencies change.

Further, the docker hub will then show users the Dockerfile that was used to build, eliminating confusion such as https://github.com/prosody/prosody-docker/issues/20

**Comment by mwild1** [comment]
Thanks, it looks like our nightly Docker builds are failing, I'll look into it.

I've also looked into Docker Hub's automated builds before, but for a number of reasons they're not really a good fit.

**Comment by mwild1** [comment]
Fixed, thanks for the report!
