### ISSUE TITLE
"docker: layers from manifest don't match image configuration." error for tagged prosody images over than :latest

### ISSUE THREAD

**Issue by unclev** [prosody/prosody-docker#29]
Trying to run any of tagged prosody/prosody container over than :latest returns "docker: layers from manifest don't match image configuration." error for tagged prosody images over than :latest.
This is the known docker 1.10+ issue docker/distribution#1439 , but I do not know whether it is possible fixing this on my side.
The actions I did to reproduce the issue:

```
victor@srv:~$ docker run -it prosody/prosody /bin/bash
Unable to find image 'prosody/prosody:latest' locally
latest: Pulling from prosody/prosody

a3ed95caeb02: Pull complete 
7cb50bcc66fd: Pull complete 
05760224df79: Pull complete 
1b71982d8bbf: Pull complete 
aa076096cff1: Pull complete 
58140e11f232: Pull complete 
f034057849a9: Pull complete 
55c05954ca0f: Pull complete 
1558887b3c27: Pull complete 
0717b57ab28b: Pull complete 
Digest: sha256:4bc36456ab4b0ac31db74c0d66f756198f87c01fe988653cbd2038912c1ee7da
Status: Downloaded newer image for prosody/prosody:latest
root@18236daeaefb:/# prosody
general             info    Hello and welcome to Prosody version 0.9.9
[...]
root@18236daeaefb:/# exit
exit
victor@srv:~$ docker run -it prosody/prosody:0.10 /bin/bash
Unable to find image 'prosody/prosody:0.10' locally
0.10: Pulling from prosody/prosody

a3ed95caeb02: Already exists 
7cb50bcc66fd: Already exists 
05760224df79: Already exists 
1b71982d8bbf: Already exists 
aa076096cff1: Already exists 
58140e11f232: Already exists 
5cafc413e997: Pull complete 
e7c8b9aee57c: Pull complete 
5e3feaed06e1: Pull complete 
3d681391fc49: Pull complete 
160bda94dc2a: Pull complete 
docker: layers from manifest don't match image configuration.
See 'docker run --help'.
victor@srv:~$ docker run -it prosody/prosody:trunk /bin/bash
Unable to find image 'prosody/prosody:trunk' locally
trunk: Pulling from prosody/prosody
a3ed95caeb02: Already exists 
7cb50bcc66fd: Already exists 
05760224df79: Already exists 
1b71982d8bbf: Already exists 
aa076096cff1: Already exists 
58140e11f232: Already exists 
d17b1acac483: Pull complete 
4fa4d4a5be84: Pull complete 
aaf485a4fa4b: Pull complete 
3d681391fc49: Pull complete 
160bda94dc2a: Pull complete 
docker: layers from manifest don't match image configuration.
See 'docker run --help'.
victor@srv:~$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
```

Could you please fix?
I do not tend to downgrade my docker-engine.

**Comment by arthos** [comment]
i second that.
its not possible to pull prosody from recent docker versions in general.
tested with recent docker on gentoo, arch and stable coreos.
same ref, same error here. this is only fixable by the pusher, in this case: the prosody team.
the procedure to fix is mentioned in the bug cited by unclev.
thanx a lot! :)

**Comment by Zalvex** [comment]
I'm having the same problem, tried to fix it downgrading my Docker version (to 1.8.1) but didn't work out.

**Comment by mwild1** [comment]
Thanks for the report. I read through the bug filed against Docker, and it's still marked as open. I don't really understand what the underlying problem is.

The workaround is just to delete all our images in the registry?

**Comment by arthos** [comment]
yes, it seems that fixed it for "dustinmoris"  at the end of the thread of the bug report.
well i hold thumbs :D

**Comment by unclev** [comment]
Thank you for working on it.
Meanwhile I used a direct ancestor of [prosody-docker-extended](https://github.com/unclev/prosody-docker-extended).

**Comment by agnauck** [comment]
same problem here, cannot use trunk or 0.10 tags. Is there any update?

**Comment by JonnyHeavey** [comment]
Also seeing the same here

**Comment by cluxter** [comment]
Same here. That is seriously annoying. Docker is supposed to avoid these kind of problems. How come the official Prosody image doesn't work with the official latest Docker release? I don't get it.

**Comment by unclev** [comment]
@mwild1, I have an idea.
As far as I understand the official ubuntu:14.04 docker image causes the issue.
May it be re-building the images forcing docker to pull the base image would solve the problem?
in [build-docker.sh](https://github.com/prosody/prosody-docker/blob/master/build-docker.sh#L15-L18):
```bash
docker build --pull -t prosody/prosody:"$i" .
```
(or just replacing ubuntu:14.04 on your docker host with the new ubuntu:14.04 image).
Updating the docker engine to a newer version may also be need.

**Comment by mbirth** [comment]
Just ran into this problem. I'll have a candle ready when this issue turns 1 year old…

**Comment by brugnara** [comment]
Hi everyone. 

I have created a working version. It is the very same as the original one but built with a recent version of docker-engine. I have tested with docker-engine 1.12.6 and I am able to pull and start the image.

I started from the original Dockerfile but I have used debian:jessie instead of ubuntu:14. All the rest remains the very same except for the installation method which relies now to a very simple `apt-get install -y prosody` from the official apt repository provided by prosody it self.

Hope this helps.

Links: 
https://github.com/futur3/prosody-docker
https://hub.docker.com/r/freeluna/prosody/

**Comment by unclev** [comment]
@brugnara, as far as I understand the main advantage of this official prosody/prosody-docker image, which you forked, is that it updates automatically when the Prosody version changes.
Are you going to update your image on the same basis?

Even though [unclev/prosody-docker-extended](unclev/prosody-docker-extended) is not the official image fork, and it is based on ubuntu:xenial, - it also updates shortly after new Prosody version built, and prosody-docker-extended:0.10 is working to me.

Links:
https://github.com/unclev/prosody-docker-extended
https://hub.docker.com/r/unclev/prosody-docker-extended/

**Comment by Zash** [comment]
I've deleted the cached Ubuntu images from the build server.

**Comment by Zash** [comment]
Rebuild of all current tags in progress. Can someone test and verify that this fixes the issue?

**Comment by mbirth** [comment]
Looking good! Before:

```
root@DiskStation:~# docker pull prosody/prosody:latest
latest: Pulling from prosody/prosody
a3ed95caeb02: Pull complete
7cb50bcc66fd: Pull complete
05760224df79: Pull complete
1b71982d8bbf: Pull complete
aa076096cff1: Pull complete
58140e11f232: Pull complete
58e4314cdfd9: Pull complete
9666ae5c460a: Pull complete
c3945b612423: Pull complete
3d681391fc49: Pull complete
160bda94dc2a: Pull complete
layers from manifest don't match image configuration
```

Now:

```
root@DiskStation:~# docker pull prosody/prosody:latest
latest: Pulling from prosody/prosody
c60055a51d74: Pull complete
755da0cdb7d2: Pull complete
969d017f67e6: Pull complete
37c9a9113595: Pull complete
a3d9f8479786: Pull complete
9cbe1bf0551d: Pull complete
3a536cd2ade8: Pull complete
2081f4ecd539: Pull complete
3d681391fc49: Pull complete
160bda94dc2a: Pull complete
Digest: sha256:7175ff3c3b01aa18637cec84910902f418f4d2d36dcd85489cb044d76ddbcafb
Status: Downloaded newer image for prosody/prosody:latest
```

**Comment by Zash** [comment]
Thanks for testing.
