### ISSUE TITLE
Image Layer Badge

### ISSUE THREAD

**Issue by lloydwatkin** [prosody/prosody-docker#31]
> We saw your image on Docker Hub at prosody/prosody, and we thought you might like this badge for your Docker Hub page showing the image contents. 
> 
> It's similar to the ImageLayers badges you may have seen, but unfortunately that is broken for images built with V2 of the Registry API. We love the information that ImageLayers provided and we decided to build something similar into MicroBadger.  
> 
> You can get a badge that shows the number of layers and download size of your Docker image, and links to our site where you can see the contents of each layer.
> 
> If you’d like to use our badge here’s the markdown - you can simply paste this into the full description for prosody/prosody on Docker Hub.
> 
> [![](https://images.microbadger.com/badges/image/prosody/prosody.svg)](https://microbadger.com/images/prosody/prosody)
> 
> If you have any questions, problems or feedback please just hit reply, or let us know through our issues list.
> 
> Best regards,
> Liz, Anne & Ross 
> Microscaling Systems

**Comment by mwild1** [comment]
Not sure how useful this is (the hub page already shows size, and layer count is not that useful), or what their business model is in spamming projects, or what they do with the data collected from the hits on these images.

Going to close unless someone can give a good reason to use this :)
