### ISSUE TITLE
documentation on configuring authentication modules

### ISSUE THREAD

**Issue by johansmitsnl** [prosody/prosody-docker#36]
I want to switch from a normal prosody install to a docker container.
The authentication is done by sasl and how can this be configured for the container?
Override all config files seems not ok and consistent.

A lot of docker applications can be configured through the ENV but this container seems to need a "real" config file with all configurations. This does not seems to be feature proof in case of a update of the config file between container versions.

Would like to see that input I can give to make this help the project or how others solved this.

**Comment by mwild1** [comment]
Hi, thanks for the report, and sorry it's taken so long to process it. There isn't really anything actionable here. There is nothing special about running Prosody in Docker, except that it is running in Docker. As you noted, even the config file is the same.

Regarding using environment variables for configuration, we're not going to attempt that here, it's not (currently?) the goal of the image. However there are alternatives linked from the README now that offer such a setup.

We always aim to preserve config file compatibility between major versions, so this is not a concern in itself.

I'm going to close this issue, but happy to discuss further if you still have questions/comments.

**Comment by johan-smits** [comment]
@mwild1 I made my own repo.
If interested you can take a look: https://github.com/johansmitsnl/docker-prosody

**Comment by johansmitsnl** [comment]
@mwild1 I made my own repo.
If interested you can take a look: https://github.com/johansmitsnl/docker-prosody
