### ISSUE TITLE
Something broken with user creation on new "0.10" branch ?

### ISSUE THREAD

**Issue by inkhey** [prosody/prosody-docker#38]
hello all. I'm trying to have jitsi-meet working with :
https://github.com/matrix-org/docker-jitsi
but with new 0.10 prosody.

jicofo is both a component and a client of prosody and have to connect to prosody server without any encryption (you need to configure prosody to disable it) .

With old 0.9.12 prosody docker , jicofo has no problem to connect to prosody, but with the same config with new 0.10 prosody docker, it clearly doesn't work anymore for connection as a client (component connection has no problems) :

```
prosody_1      | c2s2313270                     info	Client disconnected: connection closed
prosody_1      | c2s22ee0d0                     info	Client connected
jicofo_1       | Jicofo 2017-10-10 14:25:04.298 SEVERE: [16] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.log() Failed to connect/login: service-unavailable(-1)
jicofo_1       | service-unavailable(-1)

```

Maybe a problem with env params to create initial user ? Or a new politic about encryption in prosody ?

**Comment by mwild1** [comment]
Hi, I appreciate this is quite an old issue, but do you have any further information here? Did you get it working?

As it stands this issue is more of a question than a bug report, so I'll close it if I don't hear back. Thanks!

**Comment by Zash** [comment]
No response for over a year, closing.
