### ISSUE TITLE
Latest Image broken

### ISSUE THREAD

**Issue by Loader23** [prosody/prosody-docker#42]
The latest Image is broken. Starting the container will result in an error and the container stops.

"Couldn't write pidfile at /var/run/prosody/prosody.pid; /var/run/prosody/prosody.pid: No such file or directory"

**Comment by Loader23** [comment]
Maybe this helps:

https://github.com/unclev/prosody-docker-extended/issues/1

**Comment by HNieme** [comment]
Seems like prosody does not have write access to /var/run/prosody/ ?

I set the following option in the pidfile, now it works:
-- Required for init scripts and prosodyctl
-- pidfile = "/var/run/prosody/prosody.pid"
pidfile = "prosody.pid"

https://prosody.im/doc/prosodyctl#pidfile

**Comment by xsteadfastx** [comment]
the pidfile shouldnt be needed at all... cause prosody is started without a init system.

**Comment by Loader23** [comment]
Yeah, it also took me a while to figure that out, sorry for not reporting back earlier.
I got it like that:
pidfile = "/var/log/prosody/prosody.pid"
Also its important to have daemonize = false. Had to be on true before I switched to Docker so I had troubles with this setting. The documentation is not very good for Prosody Docker..
Iam closing this Issue, since its not really broken but suffers from bad maintenance https://github.com/prosody/prosody-docker/issues/44 and documentation. But still a great software though.

**Comment by chaseadam** [comment]
still getting this error and appears to be duplicate of #45 , is there a reason why we closed this without fixing the default image and launch example?

**Comment by zeropointo** [comment]
This and the Lua error mentioned in #45 are still a problem in the latest version.

**Comment by zeropointo** [comment]
FYI, using prosody/prosody:0.9 was the only solution that worked for me.

**Comment by paioniu** [comment]
It may be late, but for someone that get this same problem in future:

In mod_posix.lua module, prosody aways try to open or create the pidfile. As the default file is '/run/prosody/prosody.pid' posix module does not care if there exists the pidfile containing directory  (/run/prosody). And that directory is removed when the service is stopped. So, posix module will always raise an error  when we try to start/restart with prosodyctl on ubuntu. 

The right way of starting/restarting prosody in ubuntu is '$ sudo /etc/init.d/prosody start/restart'. The init script will create the dir '/run/prosody' so the posix module will not crash this way. I hope this can help in some cases.

**Comment by Zash** [comment]
Under Docker there is normally only one process running, so there is no purpose to having a pidfile, best leave it out of the config you mount in.
