### ISSUE TITLE
WARNING: Inofficial prosody Dockerfile

### ISSUE THREAD

**Issue by HNieme** [prosody/prosody-docker#43]
It seems that this repository is not official, as prosody is not represented as an organization on github
(See https://prosody.im/source/start)

This should be explicitly mentioned in the description of this repository!

**Comment by sapkra** [comment]
FYI
https://prosody.im/doc/docker

**Comment by mwild1** [comment]
Sorry for the confusion. The Prosody source code is not hosted on Github, however the 'prosody' organization on Github *is* owned by the Prosody team. We do use Github for a couple of peripheral projects such as this.
