### ISSUE TITLE
Prosody not working

### ISSUE THREAD

**Issue by Horstexplorer** [prosody/prosody-docker#45]
Hey the docker isnt working at the moment.

-> LuaExpat should be updated to >1.3.0
-> mod_posix Couldn't write pidfile at /var/run/prosody/prosody.pid No such file or direcory -> unable to start

**Comment by Zash** [comment]
In our latest Debian packages, which the docker images are based on, the pidfile directory is created by the init script before start. Since the docker script is not using those it would need to create this itself.

**Comment by chaseadam** [comment]
still running into this
