### ISSUE TITLE
Update 'latest' on Docker Hub

### ISSUE THREAD

**Issue by Loader23** [prosody/prosody-docker#52]
Hi,

latest Image is 7 months old. There are also no Tags for 0.11 and 0.10.3.

**Comment by mwild1** [comment]
I'm not sure why, but our build server stopped doing this. I'll keep digging...

**Comment by mwild1** [comment]
I tweaked a few things that hopefully fix it (including updating the base image to Debian stretch, as the current Ubuntu one goes EOL in a few months).

Unfortunately we won't know if the automation works again until next time we make a release, but fingers crossed!

Meanwhile, I tricked it into building 0.11.2 which has updated the 0.11.2 and the 'latest' tag, as requested by this issue, so I'll go ahead and close it. Hope this helps!
