### ISSUE TITLE
Can this image be deployed multiple times for failover/load balancing?

### ISSUE THREAD

**Issue by c00** [prosody/prosody-docker#58]
Can this image be spun up multiple times for use in Kubernetes or Docker Swarm? And if so, is it stateless?

**Comment by Zash** [comment]
Load balancing would require [clustering support](https://issues.prosody.im/413), which isn't ready yet.

If you are very careful it may be possible to do a failover setup, if one makes sure to only have one node serving clients at any time. Otherwise you will get split-brain syndrome.
