### ISSUE TITLE
Base container off Debian 10

### ISSUE THREAD

**Issue by penguineer** [prosody/prosody-docker#61]
Please update the container so that the most current Debian version will be used.

**Comment by Zash** [comment]
Any specific reason why you want this?

**Comment by penguineer** [comment]
It's the most recent stable version (including sec fixes) and it means that I don't need to have a Debian 9 image anymore. :)

Thanks for resolving the issue!

**Comment by Zash** [comment]
Debian 9 is still supported and receiving security updates tho. How that affects containers I have no idea. Prosody doesn't have a lot of dependencies, so not a lot changes from Debian 9 to 10. The main benefit I can think of is that a newer OpenSSL gives TLS 1.3 support, and it'll probably be easier to switch the `trunk` nightlies to Lua 5.3.
