### ISSUE TITLE
Image doesn't support ldap auth

### ISSUE THREAD

**Issue by r3pek** [prosody/prosody-docker#71]
When starting the `0.11` docker image with `authentication = "ldap"`, prosody complains about missing lualdap module:

`modulemanager [1;31merror[0m Error initializing module 'auth_ldap' on '<domain>': /usr/lib/prosody/util/startup.lua:207: module 'lualdap' not found:`

**Comment by Zash** [comment]
As stated in the chat, unlikely to be done as long as Prosody [lacks LDAP support](https://issues.prosody.im/54) without [3rd party modules](https://modules.prosody.im/mod_auth_ldap.html). I suggest you make your own Docker image and customize the installed dependencies.

**Comment by kostix** [comment]
@Zash, it appears that `mod_auth_ldap` [has been incorporated into Prosody](https://issues.prosody.im/54#comment-17) — at least I see it in `/usr/lib/prosody/modules` of the image tagged 13.0.

Debian 13 "Trixie" also provides stock `lua-ldap` module, so it appears that the fix would be a one-line change to the Dockerfile.

Can we reopen the issue, please?
